-- ============================================================
-- Sipomax: full schema migration for a fresh Supabase project
-- Generated by concatenating supabase/migrations/*.sql in order
-- (53 migrations, regenerated 2026-07-12)
-- Run in: Supabase Dashboard -> SQL Editor -> New query -> Run
--
-- BEFORE RUNNING: search for YOUR_PROJECT_REF below and replace
-- it with your new project's ref (the xxxx in https://xxxx.supabase.co).
-- ============================================================


-- ------------------------------------------------------------
-- File: 20260518123911_0f537043-7410-43c1-a5ae-779e0f7e2b9e.sql
-- ------------------------------------------------------------


-- Enums
CREATE TYPE public.app_role AS ENUM ('workshop', 'admin');
CREATE TYPE public.job_status AS ENUM ('started_work', 'quote_sent', 'quote_approved', 'quote_rejected', 'in_progress', 'job_done');
CREATE TYPE public.sender_type AS ENUM ('workshop', 'customer');
CREATE TYPE public.approval_state AS ENUM ('pending', 'approved', 'rejected');

-- Profiles
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- User roles
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, role)
);
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- has_role function
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role
  )
$$;

-- Auto-create profile + workshop role on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)));
  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'workshop');
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Jobs
CREATE TABLE public.jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_token TEXT NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(16), 'hex'),
  registration_number TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  vehicle_make TEXT,
  vehicle_model TEXT,
  notes TEXT,
  current_status public.job_status NOT NULL DEFAULT 'started_work',
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_jobs_token ON public.jobs(job_token);
CREATE INDEX idx_jobs_reg ON public.jobs(lower(registration_number));

-- Status updates
CREATE TABLE public.status_updates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  status public.job_status NOT NULL,
  description TEXT,
  requires_approval BOOLEAN NOT NULL DEFAULT false,
  approval_state public.approval_state,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.status_updates ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_status_updates_job ON public.status_updates(job_id, created_at);

-- Attachments
CREATE TABLE public.status_update_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status_update_id UUID NOT NULL REFERENCES public.status_updates(id) ON DELETE CASCADE,
  file_path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  mime_type TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.status_update_attachments ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_attachments_update ON public.status_update_attachments(status_update_id);

-- Messages
CREATE TABLE public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  sender_type public.sender_type NOT NULL,
  sender_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_messages_job ON public.messages(job_id, created_at);

-- RLS Policies — workshop role can do everything; customer access is via server fns (admin client)

-- profiles
CREATE POLICY "Workshop can view all profiles" ON public.profiles FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'workshop'));
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT TO authenticated
  USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = id);

-- user_roles
CREATE POLICY "Users can view own roles" ON public.user_roles FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

-- jobs
CREATE POLICY "Workshop manages jobs" ON public.jobs FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop'))
  WITH CHECK (public.has_role(auth.uid(), 'workshop'));

-- status_updates
CREATE POLICY "Workshop manages status updates" ON public.status_updates FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop'))
  WITH CHECK (public.has_role(auth.uid(), 'workshop'));

-- attachments
CREATE POLICY "Workshop manages attachments" ON public.status_update_attachments FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop'))
  WITH CHECK (public.has_role(auth.uid(), 'workshop'));

-- messages
CREATE POLICY "Workshop manages messages" ON public.messages FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop'))
  WITH CHECK (public.has_role(auth.uid(), 'workshop'));

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.status_updates;
ALTER PUBLICATION supabase_realtime ADD TABLE public.jobs;

-- Storage bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('job-attachments', 'job-attachments', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Workshop can upload attachments" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'job-attachments' AND public.has_role(auth.uid(), 'workshop'));
CREATE POLICY "Workshop can manage attachments" ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'job-attachments' AND public.has_role(auth.uid(), 'workshop'));
CREATE POLICY "Public can read attachments" ON storage.objects FOR SELECT TO anon, authenticated
  USING (bucket_id = 'job-attachments');


-- ------------------------------------------------------------
-- File: 20260518123934_135e1b22-ee1d-45db-8feb-b2249a9b4f89.sql
-- ------------------------------------------------------------


REVOKE EXECUTE ON FUNCTION public.has_role(UUID, public.app_role) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
DROP POLICY IF EXISTS "Public can read attachments" ON storage.objects;


-- ------------------------------------------------------------
-- File: 20260518125612_2667260d-18fd-46ae-809c-a873b06cc947.sql
-- ------------------------------------------------------------

GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;

-- ------------------------------------------------------------
-- File: 20260518131032_449bee8a-b6f2-422b-8b33-6b12c4f9a332.sql
-- ------------------------------------------------------------

ALTER TABLE public.status_updates ADD COLUMN quote_amount NUMERIC(10,2);

-- ------------------------------------------------------------
-- File: 20260519101332_11e125ec-1ce8-4bd2-97b1-589d017530fb.sql
-- ------------------------------------------------------------


ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS customer_org_number text,
  ADD COLUMN IF NOT EXISTS customer_email text,
  ADD COLUMN IF NOT EXISTS billing_address text,
  ADD COLUMN IF NOT EXISTS billing_postal_code text,
  ADD COLUMN IF NOT EXISTS billing_city text,
  ADD COLUMN IF NOT EXISTS invoice_scheduled_at timestamptz,
  ADD COLUMN IF NOT EXISTS invoice_generated_at timestamptz,
  ADD COLUMN IF NOT EXISTS visma_invoice_id text,
  ADD COLUMN IF NOT EXISTS invoice_error text;

-- Trigger: when a job's current_status first becomes 'job_done', schedule invoice 5 days out
CREATE OR REPLACE FUNCTION public.schedule_visma_invoice()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.current_status = 'job_done'
     AND (OLD.current_status IS DISTINCT FROM 'job_done')
     AND NEW.invoice_scheduled_at IS NULL
     AND NEW.invoice_generated_at IS NULL THEN
    NEW.invoice_scheduled_at := now() + interval '5 days';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_schedule_visma_invoice ON public.jobs;
CREATE TRIGGER trg_schedule_visma_invoice
BEFORE UPDATE ON public.jobs
FOR EACH ROW EXECUTE FUNCTION public.schedule_visma_invoice();

-- Visma per-user OAuth connections
CREATE TABLE IF NOT EXISTS public.visma_connections (
  user_id uuid PRIMARY KEY,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamptz NOT NULL,
  environment text NOT NULL DEFAULT 'sandbox' CHECK (environment IN ('sandbox','production')),
  company_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.visma_connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own visma connection"
ON public.visma_connections
FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Enable extensions for cron
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;


-- ------------------------------------------------------------
-- File: 20260519101348_6fac68b3-7e9f-459e-92cb-5d4d832ad025.sql
-- ------------------------------------------------------------


REVOKE EXECUTE ON FUNCTION public.schedule_visma_invoice() FROM PUBLIC, anon, authenticated;


-- ------------------------------------------------------------
-- File: 20260519131253_e7c8dbca-3f07-4106-b5f0-c15d920aabea.sql
-- ------------------------------------------------------------

ALTER TYPE public.job_status ADD VALUE IF NOT EXISTS 'car_dropped_off' BEFORE 'started_work';
ALTER TYPE public.job_status ADD VALUE IF NOT EXISTS 'car_picked_up';
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS google_review_url TEXT;

-- ------------------------------------------------------------
-- File: 20260519132407_1b744b63-6851-4596-b912-c3497778987e.sql
-- ------------------------------------------------------------

ALTER TYPE public.job_status ADD VALUE IF NOT EXISTS 'diagnosis_started';

-- ------------------------------------------------------------
-- File: 20260520143443_6cc15b3b-4470-49f1-8f7b-f668a225a871.sql
-- ------------------------------------------------------------


ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS vehicle_color text,
  ADD COLUMN IF NOT EXISTS vehicle_type text,
  ADD COLUMN IF NOT EXISTS vehicle_status text,
  ADD COLUMN IF NOT EXISTS owner_count integer,
  ADD COLUMN IF NOT EXISTS last_inspection_date date,
  ADD COLUMN IF NOT EXISTS next_inspection_date date,
  ADD COLUMN IF NOT EXISTS mileage integer;


-- ------------------------------------------------------------
-- File: 20260520150553_53df6d29-28c5-423f-a71e-486400f1de94.sql
-- ------------------------------------------------------------

ALTER TABLE public.jobs
  ALTER COLUMN last_inspection_date TYPE text USING last_inspection_date::text,
  ALTER COLUMN next_inspection_date TYPE text USING next_inspection_date::text;

-- ------------------------------------------------------------
-- File: 20260520152157_4cdd91ff-7dd0-4553-8607-2f3c334ccd29.sql
-- ------------------------------------------------------------


-- Extend profiles with workshop settings
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS company_name text,
  ADD COLUMN IF NOT EXISTS contact_email text,
  ADD COLUMN IF NOT EXISTS contact_phone text,
  ADD COLUMN IF NOT EXISTS workshop_address text,
  ADD COLUMN IF NOT EXISTS invoice_delay_days integer NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS pickup_sms_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS sms_signature text;

-- Allow workshop users to insert their own profile row (needed for upsert)
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
ON public.profiles
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

-- Update the invoice scheduling trigger to use the user's preferred delay
CREATE OR REPLACE FUNCTION public.schedule_visma_invoice()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  delay_days integer := 5;
BEGIN
  IF NEW.current_status = 'job_done'
     AND (OLD.current_status IS DISTINCT FROM 'job_done')
     AND NEW.invoice_scheduled_at IS NULL
     AND NEW.invoice_generated_at IS NULL THEN
    IF NEW.created_by IS NOT NULL THEN
      SELECT COALESCE(p.invoice_delay_days, 5) INTO delay_days
      FROM public.profiles p
      WHERE p.id = NEW.created_by;
    END IF;
    NEW.invoice_scheduled_at := now() + make_interval(days => delay_days);
  END IF;
  RETURN NEW;
END;
$function$;


-- ------------------------------------------------------------
-- File: 20260520152208_dcb506a4-0eef-4246-87a0-ff9fedca1213.sql
-- ------------------------------------------------------------

REVOKE EXECUTE ON FUNCTION public.schedule_visma_invoice() FROM PUBLIC, anon, authenticated;

-- ------------------------------------------------------------
-- File: 20260520160015_8a8a571f-a598-42ce-a6ee-f2d9dd26a69c.sql
-- ------------------------------------------------------------


CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

CREATE TYPE public.opportunity_status AS ENUM ('pending', 'approved', 'sent', 'failed', 'dismissed');

CREATE TABLE public.opportunities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL,
  job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  customer_name text NOT NULL,
  customer_phone text,
  opportunity_type text NOT NULL,
  title text NOT NULL,
  reason text NOT NULL,
  suggested_message text NOT NULL,
  suggested_send_at timestamptz NOT NULL,
  status public.opportunity_status NOT NULL DEFAULT 'pending',
  sent_at timestamptz,
  send_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_opportunities_status_send ON public.opportunities(status, suggested_send_at);
CREATE INDEX idx_opportunities_created_by ON public.opportunities(created_by);

ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Workshop manages opportunities"
ON public.opportunities FOR ALL TO authenticated
USING (public.has_role(auth.uid(), 'workshop'::app_role))
WITH CHECK (public.has_role(auth.uid(), 'workshop'::app_role));

CREATE TRIGGER set_opportunities_updated_at
BEFORE UPDATE ON public.opportunities
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- ------------------------------------------------------------
-- File: 20260520160639_8ad2d16a-eaa0-40d9-9516-1c0460bb9b51.sql
-- ------------------------------------------------------------

ALTER TABLE public.jobs ADD COLUMN initial_price numeric;

-- ------------------------------------------------------------
-- File: 20260520192956_dc902941-c3f5-4e9d-8b7f-4e1e36c16e10.sql
-- ------------------------------------------------------------


DO $$ BEGIN
  CREATE TYPE public.campaign_status AS ENUM ('pending', 'approved', 'sent', 'failed', 'dismissed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS mileage_recorded_at timestamptz,
  ADD COLUMN IF NOT EXISTS mileage_source text,
  ADD COLUMN IF NOT EXISTS mileage_at_last_service integer,
  ADD COLUMN IF NOT EXISTS last_service_at timestamptz,
  ADD COLUMN IF NOT EXISTS avg_km_per_month numeric,
  ADD COLUMN IF NOT EXISTS engine_type text,
  ADD COLUMN IF NOT EXISTS engine_code text,
  ADD COLUMN IF NOT EXISTS gearbox_type text,
  ADD COLUMN IF NOT EXISTS vin text,
  ADD COLUMN IF NOT EXISTS model_year integer,
  ADD COLUMN IF NOT EXISTS recommended_service_interval_km integer,
  ADD COLUMN IF NOT EXISTS recommended_service_interval_months integer;

CREATE TABLE IF NOT EXISTS public.campaigns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL,
  campaign_type text NOT NULL,
  title text NOT NULL,
  reason text NOT NULL,
  suggested_message text NOT NULL,
  suggested_send_at timestamptz NOT NULL,
  recipients jsonb NOT NULL DEFAULT '[]'::jsonb,
  status public.campaign_status NOT NULL DEFAULT 'pending',
  sent_at timestamptz,
  send_error text,
  send_results jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Workshop manages campaigns" ON public.campaigns;
CREATE POLICY "Workshop manages campaigns" ON public.campaigns
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'workshop'::app_role));

DROP TRIGGER IF EXISTS touch_campaigns_updated_at ON public.campaigns;
CREATE TRIGGER touch_campaigns_updated_at
  BEFORE UPDATE ON public.campaigns
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- ------------------------------------------------------------
-- File: 20260520193957_0f1a3de1-f577-40a1-ad2d-0a56c7d14184.sql
-- ------------------------------------------------------------

ALTER TABLE public.opportunities
  ADD COLUMN IF NOT EXISTS trigger_message_ids uuid[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS trigger_context text;

-- ------------------------------------------------------------
-- File: 20260520204415_89fa7ca7-71f1-449b-b8a0-80fd87988483.sql
-- ------------------------------------------------------------


ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS opportunity_prompt_extra text,
  ADD COLUMN IF NOT EXISTS service_prompt_extra text,
  ADD COLUMN IF NOT EXISTS service_metrics text[];


-- ------------------------------------------------------------
-- File: 20260520210111_e3e3e8e4-4e85-451c-b97d-b61e817a3f18.sql
-- ------------------------------------------------------------

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS opportunity_prompt_base text,
  ADD COLUMN IF NOT EXISTS service_prompt_base text;

-- ------------------------------------------------------------
-- File: 20260525122800_7c4befc8-efe5-4051-acd5-b27e530f4490.sql
-- ------------------------------------------------------------


CREATE TABLE public.scandic_leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  phone text NOT NULL,
  name text,
  email text,
  question text,
  status text NOT NULL DEFAULT 'pending',
  opted_out boolean NOT NULL DEFAULT false,
  last_reminder_kind text,
  initial_sent_at timestamptz,
  booking_token text NOT NULL DEFAULT encode(gen_random_bytes(12), 'hex'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (owner_id, phone)
);
CREATE UNIQUE INDEX scandic_leads_booking_token_idx ON public.scandic_leads(booking_token);
CREATE INDEX scandic_leads_owner_idx ON public.scandic_leads(owner_id, created_at DESC);

ALTER TABLE public.scandic_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner manages scandic leads" ON public.scandic_leads
  FOR ALL TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

CREATE TRIGGER scandic_leads_touch BEFORE UPDATE ON public.scandic_leads
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TABLE public.scandic_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL REFERENCES public.scandic_leads(id) ON DELETE CASCADE,
  direction text NOT NULL,
  body text NOT NULL,
  reminder_kind text,
  elks_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX scandic_messages_lead_idx ON public.scandic_messages(lead_id, created_at);

ALTER TABLE public.scandic_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner manages scandic messages" ON public.scandic_messages
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.scandic_leads l WHERE l.id = lead_id AND l.owner_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.scandic_leads l WHERE l.id = lead_id AND l.owner_id = auth.uid()));

CREATE TABLE public.scandic_bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL REFERENCES public.scandic_leads(id) ON DELETE CASCADE,
  slot_start timestamptz NOT NULL,
  slot_end timestamptz NOT NULL,
  name text,
  email text,
  phone text,
  question text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (slot_start)
);
CREATE INDEX scandic_bookings_lead_idx ON public.scandic_bookings(lead_id);

ALTER TABLE public.scandic_bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner manages scandic bookings" ON public.scandic_bookings
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.scandic_leads l WHERE l.id = lead_id AND l.owner_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.scandic_leads l WHERE l.id = lead_id AND l.owner_id = auth.uid()));


-- ------------------------------------------------------------
-- File: 20260525123450_6e86f917-9d7b-4aef-bbd2-ef8dd634d6df.sql
-- ------------------------------------------------------------

ALTER TABLE public.scandic_bookings ADD COLUMN IF NOT EXISTS meeting_type text;

-- ------------------------------------------------------------
-- File: 20260525124226_c4e4ea15-44f7-4600-b674-70d6438adfe9.sql
-- ------------------------------------------------------------


-- 1) user_roles: explicitly deny INSERT/UPDATE/DELETE for clients (roles managed by backend only)
DROP POLICY IF EXISTS "No client inserts on user_roles" ON public.user_roles;
DROP POLICY IF EXISTS "No client updates on user_roles" ON public.user_roles;
DROP POLICY IF EXISTS "No client deletes on user_roles" ON public.user_roles;

CREATE POLICY "No client inserts on user_roles"
ON public.user_roles FOR INSERT TO authenticated, anon
WITH CHECK (false);

CREATE POLICY "No client updates on user_roles"
ON public.user_roles FOR UPDATE TO authenticated, anon
USING (false) WITH CHECK (false);

CREATE POLICY "No client deletes on user_roles"
ON public.user_roles FOR DELETE TO authenticated, anon
USING (false);

-- 2) visma_connections: tokens must never be readable from client. Drop user-facing policy.
-- Only the service role (used server-side via supabaseAdmin) should access this table.
DROP POLICY IF EXISTS "Users manage own visma connection" ON public.visma_connections;


-- ------------------------------------------------------------
-- File: 20260525130323_c8249ec5-affb-4783-aa5d-7dae18a24988.sql
-- ------------------------------------------------------------

-- Make the job-attachments bucket private
UPDATE storage.buckets SET public = false WHERE id = 'job-attachments';

-- Allow workshop role to access objects in this bucket via the authenticated client.
-- (Server-side admin client bypasses RLS regardless; this is so authenticated
--  workshop users can also read/write directly if needed.)
DROP POLICY IF EXISTS "Workshop reads job attachments" ON storage.objects;
DROP POLICY IF EXISTS "Workshop writes job attachments" ON storage.objects;
DROP POLICY IF EXISTS "Workshop updates job attachments" ON storage.objects;
DROP POLICY IF EXISTS "Workshop deletes job attachments" ON storage.objects;

CREATE POLICY "Workshop reads job attachments"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'job-attachments' AND public.has_role(auth.uid(), 'workshop'));

CREATE POLICY "Workshop writes job attachments"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'job-attachments' AND public.has_role(auth.uid(), 'workshop'));

CREATE POLICY "Workshop updates job attachments"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'job-attachments' AND public.has_role(auth.uid(), 'workshop'));

CREATE POLICY "Workshop deletes job attachments"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'job-attachments' AND public.has_role(auth.uid(), 'workshop'));

-- ------------------------------------------------------------
-- File: 20260601151658_999988a6-fb31-4ecc-b56f-65c2a521914d.sql
-- ------------------------------------------------------------

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS insights_last_seen_at timestamp with time zone NOT NULL DEFAULT now();

-- ------------------------------------------------------------
-- File: 20260601153605_2fa6fe59-e9c9-4639-811b-eedaf6202bd2.sql
-- ------------------------------------------------------------

-- Explicit deny-all policies on visma_connections so the linter sees coverage.
-- Only the service role (used by server functions/admin) can access this table.
REVOKE ALL ON public.visma_connections FROM anon, authenticated;
GRANT ALL ON public.visma_connections TO service_role;

CREATE POLICY "Deny client select" ON public.visma_connections
  FOR SELECT TO anon, authenticated USING (false);
CREATE POLICY "Deny client insert" ON public.visma_connections
  FOR INSERT TO anon, authenticated WITH CHECK (false);
CREATE POLICY "Deny client update" ON public.visma_connections
  FOR UPDATE TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY "Deny client delete" ON public.visma_connections
  FOR DELETE TO anon, authenticated USING (false);

-- ------------------------------------------------------------
-- File: 20260601160650_6b188503-f2ea-4f64-9049-7003236a49cd.sql
-- ------------------------------------------------------------

CREATE TABLE public.push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_push_subscriptions_user_id ON public.push_subscriptions(user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.push_subscriptions TO authenticated;
GRANT ALL ON public.push_subscriptions TO service_role;

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own push subscriptions select"
  ON public.push_subscriptions FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users manage own push subscriptions insert"
  ON public.push_subscriptions FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users manage own push subscriptions update"
  ON public.push_subscriptions FOR UPDATE
  TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users manage own push subscriptions delete"
  ON public.push_subscriptions FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE TRIGGER touch_push_subscriptions_updated_at
  BEFORE UPDATE ON public.push_subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ------------------------------------------------------------
-- File: 20260601175559_cc52417e-5462-432f-95f5-fdff16846269.sql
-- ------------------------------------------------------------

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS notify_customer_messages boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_pending_reminders boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS pending_reminder_last_sent_at timestamptz;

-- ------------------------------------------------------------
-- File: 20260616152048_cd560fa1-23e8-44ec-8d7f-798bf840a095.sql
-- ------------------------------------------------------------

ALTER TABLE realtime.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Workshop users can subscribe to realtime"
ON realtime.messages
FOR SELECT
TO authenticated
USING (public.has_role(auth.uid(), 'workshop'::app_role));

-- ------------------------------------------------------------
-- File: 20260617120000_fortnox.sql
-- ------------------------------------------------------------

-- Fortnox invoice integration: per-user OAuth connections + provider selection.

-- Track the Fortnox invoice/document number per job (parallel to visma_invoice_id).
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS fortnox_invoice_id text;

-- Which invoice integration is active for the user. Existing users keep Visma.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS invoice_provider text NOT NULL DEFAULT 'visma'
    CHECK (invoice_provider IN ('visma','fortnox'));

-- Fortnox per-user OAuth connections (mirrors visma_connections).
CREATE TABLE IF NOT EXISTS public.fortnox_connections (
  user_id uuid PRIMARY KEY,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamptz NOT NULL,
  environment text NOT NULL DEFAULT 'production' CHECK (environment IN ('sandbox','production')),
  company_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.fortnox_connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own fortnox connection"
ON public.fortnox_connections
FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);


-- ------------------------------------------------------------
-- File: 20260617122633_24ac6541-ade5-4ac3-8bfb-b0ca70bab5be.sql
-- ------------------------------------------------------------

-- The migration before this one created an earlier, narrower shape of this
-- table. In the original project's history that shape was replaced by hand
-- (Lovable Cloud dashboard) rather than through a captured migration, so a
-- fresh replay of this file needs an explicit drop before recreating it here.
DROP TABLE IF EXISTS public.fortnox_connections CASCADE;

CREATE TABLE public.fortnox_connections (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  environment TEXT NOT NULL DEFAULT 'production',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.fortnox_connections TO authenticated;
GRANT ALL ON public.fortnox_connections TO service_role;

ALTER TABLE public.fortnox_connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own fortnox connection"
  ON public.fortnox_connections FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own fortnox connection"
  ON public.fortnox_connections FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own fortnox connection"
  ON public.fortnox_connections FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own fortnox connection"
  ON public.fortnox_connections FOR DELETE
  USING (auth.uid() = user_id);

CREATE TRIGGER fortnox_connections_touch_updated_at
  BEFORE UPDATE ON public.fortnox_connections
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ------------------------------------------------------------
-- File: 20260617122653_a6b86839-d4f7-404d-98eb-a3bb8595b4ff.sql
-- ------------------------------------------------------------

ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS fortnox_invoice_id TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS invoice_provider TEXT NOT NULL DEFAULT 'visma';

-- ------------------------------------------------------------
-- File: 20260619120000_user_management_settings.sql
-- ------------------------------------------------------------

-- Per-user feature flags, managed by admins from the "Hantera användare"
-- settings page. Toggle visibility of the Uppföljningar (opportunities) and
-- Kampanjer (campaigns) pages/buttons for individual users.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS opportunities_enabled boolean NOT NULL DEFAULT true;
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS campaigns_enabled boolean NOT NULL DEFAULT true;


-- ------------------------------------------------------------
-- File: 20260622120000_invoice_articles.sql
-- ------------------------------------------------------------

-- Article-based offers + an editable invoice working set for the Fortnox flow.
--
-- Offers (quote_sent) are now built from Fortnox articles. Each offer stores its
-- selected article lines so the confirmed offers can seed the final invoice.
-- Shape: [{ "article_number": "10", "description": "Oljebyte", "quantity": 1,
--           "unit_price": 495, "vat": 25 }]
ALTER TABLE public.status_updates
  ADD COLUMN IF NOT EXISTS articles jsonb;

-- The editable working set of invoice rows on the "Faktura" page. Seeded from the
-- confirmed offers' articles, then adjustable (add/delete/temporary price) before
-- the invoice + customer are created in Fortnox.
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS invoice_articles jsonb;


-- ------------------------------------------------------------
-- File: 20260623120000_invoice_pdf_settings.sql
-- ------------------------------------------------------------

-- Invoice PDF settings per user profile
alter table public.profiles
  add column if not exists invoice_logo_url   text,
  add column if not exists invoice_bank_details jsonb,
  add column if not exists invoice_accent_color text default '#1a56db';

-- Public storage bucket for invoice logos
insert into storage.buckets (id, name, public)
values ('invoice-logos', 'invoice-logos', true)
on conflict (id) do nothing;

-- Anyone authenticated can upload their own logo
create policy "Users can upload their own invoice logo"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'invoice-logos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Users can update their own invoice logo"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'invoice-logos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Users can delete their own invoice logo"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'invoice-logos' and (storage.foldername(name))[1] = auth.uid()::text);

-- Public read for logos (they appear on invoices)
create policy "Public read invoice logos"
  on storage.objects for select
  to public
  using (bucket_id = 'invoice-logos');


-- ------------------------------------------------------------
-- File: 20260624120000_company_info_fields.sql
-- ------------------------------------------------------------

-- Company info fields for invoice PDF generation
alter table public.profiles
  add column if not exists company_zip_code   text,
  add column if not exists company_city       text,
  add column if not exists company_org_number text,
  add column if not exists company_vat_number text;


-- ------------------------------------------------------------
-- File: 20260624120000_tenant_isolation_rls.sql
-- ------------------------------------------------------------

-- Tenant isolation: tighten RLS so each workshop account can only access its
-- own rows. Previously all workshop-role users could read/write all rows.
-- Server functions use the admin client (bypasses RLS) so these policies are a
-- defense-in-depth layer that also protects direct Supabase client calls and
-- Realtime channel subscriptions from the workshop UI.

-- jobs: restrict to the creating user
DROP POLICY IF EXISTS "Workshop manages jobs" ON public.jobs;
CREATE POLICY "Workshop manages own jobs" ON public.jobs
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop') AND created_by = auth.uid())
  WITH CHECK (public.has_role(auth.uid(), 'workshop') AND created_by = auth.uid());

-- status_updates: restrict via parent job ownership
DROP POLICY IF EXISTS "Workshop manages status updates" ON public.status_updates;
CREATE POLICY "Workshop manages own status updates" ON public.status_updates
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = status_updates.job_id AND jobs.created_by = auth.uid()
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = status_updates.job_id AND jobs.created_by = auth.uid()
    )
  );

-- status_update_attachments: restrict via status_update → job chain
DROP POLICY IF EXISTS "Workshop manages attachments" ON public.status_update_attachments;
CREATE POLICY "Workshop manages own attachments" ON public.status_update_attachments
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.status_updates su
      JOIN public.jobs j ON j.id = su.job_id
      WHERE su.id = status_update_attachments.status_update_id AND j.created_by = auth.uid()
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.status_updates su
      JOIN public.jobs j ON j.id = su.job_id
      WHERE su.id = status_update_attachments.status_update_id AND j.created_by = auth.uid()
    )
  );

-- messages: restrict via parent job ownership
DROP POLICY IF EXISTS "Workshop manages messages" ON public.messages;
CREATE POLICY "Workshop manages own messages" ON public.messages
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = messages.job_id AND jobs.created_by = auth.uid()
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = messages.job_id AND jobs.created_by = auth.uid()
    )
  );

-- opportunities: restrict to the creating user
DROP POLICY IF EXISTS "Workshop manages opportunities" ON public.opportunities;
DROP POLICY IF EXISTS "Workshop can read opportunities" ON public.opportunities;
DROP POLICY IF EXISTS "Workshop can create opportunities" ON public.opportunities;
DROP POLICY IF EXISTS "Workshop can update opportunities" ON public.opportunities;
CREATE POLICY "Workshop manages own opportunities" ON public.opportunities
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop') AND created_by = auth.uid())
  WITH CHECK (public.has_role(auth.uid(), 'workshop') AND created_by = auth.uid());

-- campaigns: restrict to the creating user
DROP POLICY IF EXISTS "Workshop manages campaigns" ON public.campaigns;
CREATE POLICY "Workshop manages own campaigns" ON public.campaigns
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'workshop') AND created_by = auth.uid())
  WITH CHECK (public.has_role(auth.uid(), 'workshop') AND created_by = auth.uid());


-- ------------------------------------------------------------
-- File: 20260624140000_workshop_multiuser.sql
-- ------------------------------------------------------------

-- Multi-user workshop architecture.
-- Each workshop owner can invite team members who share the same data.
-- A new workshop_id column (set to the owner's user ID) replaces per-user
-- created_by scoping. Team membership is tracked via account_owner_id on profiles.
-- Developer impersonation is tracked via impersonating_workshop_id on profiles.

-- profiles: multi-user workshop columns
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS account_owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS impersonating_workshop_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_profiles_account_owner ON public.profiles(account_owner_id);

-- jobs
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS workshop_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
UPDATE public.jobs SET workshop_id = created_by WHERE workshop_id IS NULL AND created_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_jobs_workshop ON public.jobs(workshop_id);

-- opportunities
ALTER TABLE public.opportunities
  ADD COLUMN IF NOT EXISTS workshop_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
UPDATE public.opportunities SET workshop_id = created_by WHERE workshop_id IS NULL AND created_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_opportunities_workshop ON public.opportunities(workshop_id);

-- campaigns
ALTER TABLE public.campaigns
  ADD COLUMN IF NOT EXISTS workshop_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
UPDATE public.campaigns SET workshop_id = created_by WHERE workshop_id IS NULL AND created_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_campaigns_workshop ON public.campaigns(workshop_id);

-- Helper: returns true if _user_id owns or is a member of _workshop_id
CREATE OR REPLACE FUNCTION public.is_workshop_member(_user_id UUID, _workshop_id UUID)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
    _user_id = _workshop_id OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = _user_id AND account_owner_id = _workshop_id
    )
$$;

-- Update RLS to use workshop_id + is_workshop_member

-- jobs
DROP POLICY IF EXISTS "Workshop manages own jobs" ON public.jobs;
CREATE POLICY "Workshop manages workshop jobs" ON public.jobs
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    public.is_workshop_member(auth.uid(), workshop_id)
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    public.is_workshop_member(auth.uid(), workshop_id)
  );

-- status_updates: scope via parent job's workshop_id
DROP POLICY IF EXISTS "Workshop manages own status updates" ON public.status_updates;
CREATE POLICY "Workshop manages workshop status updates" ON public.status_updates
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = status_updates.job_id
        AND public.is_workshop_member(auth.uid(), jobs.workshop_id)
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = status_updates.job_id
        AND public.is_workshop_member(auth.uid(), jobs.workshop_id)
    )
  );

-- attachments: scope via status_update → job chain
DROP POLICY IF EXISTS "Workshop manages own attachments" ON public.status_update_attachments;
CREATE POLICY "Workshop manages workshop attachments" ON public.status_update_attachments
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.status_updates su
      JOIN public.jobs j ON j.id = su.job_id
      WHERE su.id = status_update_attachments.status_update_id
        AND public.is_workshop_member(auth.uid(), j.workshop_id)
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.status_updates su
      JOIN public.jobs j ON j.id = su.job_id
      WHERE su.id = status_update_attachments.status_update_id
        AND public.is_workshop_member(auth.uid(), j.workshop_id)
    )
  );

-- messages: scope via parent job's workshop_id
DROP POLICY IF EXISTS "Workshop manages own messages" ON public.messages;
CREATE POLICY "Workshop manages workshop messages" ON public.messages
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = messages.job_id
        AND public.is_workshop_member(auth.uid(), jobs.workshop_id)
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    EXISTS (
      SELECT 1 FROM public.jobs
      WHERE jobs.id = messages.job_id
        AND public.is_workshop_member(auth.uid(), jobs.workshop_id)
    )
  );

-- opportunities
DROP POLICY IF EXISTS "Workshop manages own opportunities" ON public.opportunities;
CREATE POLICY "Workshop manages workshop opportunities" ON public.opportunities
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    public.is_workshop_member(auth.uid(), workshop_id)
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    public.is_workshop_member(auth.uid(), workshop_id)
  );

-- campaigns
DROP POLICY IF EXISTS "Workshop manages own campaigns" ON public.campaigns;
CREATE POLICY "Workshop manages workshop campaigns" ON public.campaigns
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'workshop') AND
    public.is_workshop_member(auth.uid(), workshop_id)
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'workshop') AND
    public.is_workshop_member(auth.uid(), workshop_id)
  );


-- ------------------------------------------------------------
-- File: 20260624160000_immediate_invoicing.sql
-- ------------------------------------------------------------

-- Remove the configurable invoice delay. Invoices are now scheduled
-- immediately when a job is marked done (the cron picks them up on its next
-- run), and the manual "generera faktura" action already runs immediately.

-- Schedule the invoice for "now" instead of now() + delay_days.
CREATE OR REPLACE FUNCTION public.schedule_visma_invoice()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.current_status = 'job_done'
     AND (OLD.current_status IS DISTINCT FROM 'job_done')
     AND NEW.invoice_scheduled_at IS NULL
     AND NEW.invoice_generated_at IS NULL THEN
    NEW.invoice_scheduled_at := now();
  END IF;
  RETURN NEW;
END;
$function$;

-- The delay setting no longer exists.
ALTER TABLE public.profiles DROP COLUMN IF EXISTS invoice_delay_days;


-- ------------------------------------------------------------
-- File: 20260624170000_pickup_sms_review.sql
-- ------------------------------------------------------------

-- Add configurable review-request toggle and message to the pickup SMS feature.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS pickup_sms_review_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS pickup_sms_review_message text;


-- ------------------------------------------------------------
-- File: 20260625130000_identifier_type.sql
-- ------------------------------------------------------------

ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS identifier_type TEXT NOT NULL DEFAULT 'registration'
    CHECK (identifier_type IN ('registration', 'article'));


-- ------------------------------------------------------------
-- File: 20260625140000_notify_push_device_prefs.sql
-- ------------------------------------------------------------

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS notify_mobile_push BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_desktop_push BOOLEAN NOT NULL DEFAULT TRUE;


-- ------------------------------------------------------------
-- File: 20260626120000_order_received_chat_sms.sql
-- ------------------------------------------------------------

-- Add order_received to the job_status enum
ALTER TYPE job_status ADD VALUE IF NOT EXISTS 'order_received';

-- Chat SMS throttling columns on jobs
ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS last_chat_sms_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS pending_chat_reminder_at TIMESTAMPTZ;

-- Index for cron job picking up due reminders
CREATE INDEX IF NOT EXISTS idx_jobs_pending_chat_reminder
  ON jobs (pending_chat_reminder_at)
  WHERE pending_chat_reminder_at IS NOT NULL;


-- ------------------------------------------------------------
-- File: 20260626150000_fortnox_local_cache.sql
-- ------------------------------------------------------------

-- Local cache of Fortnox customers and articles, per workshop.
--
-- Searching customers/articles previously hit the Fortnox API on every
-- keystroke/focus (fetching up to 500 customers / 200 articles each time).
-- These tables mirror the workshop's Fortnox data so search runs against the
-- local database instead. They are refreshed in the background when stale and
-- updated immediately whenever a customer/article is created or edited.

CREATE TABLE IF NOT EXISTS public.fortnox_customers_cache (
  workshop_id     uuid NOT NULL,
  customer_number text NOT NULL,
  name            text,
  email           text,
  phone           text,
  org_number      text,
  address         text,
  zip_code        text,
  city            text,
  -- Precomputed lowercase haystack (name, number, email, org nr, address, city,
  -- and phone digit variants) so search is a single ILIKE.
  search_text     text,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workshop_id, customer_number)
);

CREATE INDEX IF NOT EXISTS fortnox_customers_cache_search_idx
  ON public.fortnox_customers_cache (workshop_id);

CREATE TABLE IF NOT EXISTS public.fortnox_articles_cache (
  workshop_id    uuid NOT NULL,
  article_number text NOT NULL,
  description    text,
  sales_price    numeric,
  unit           text,
  vat            numeric,
  search_text    text,
  updated_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workshop_id, article_number)
);

CREATE INDEX IF NOT EXISTS fortnox_articles_cache_search_idx
  ON public.fortnox_articles_cache (workshop_id);

-- Tracks when each cache kind was last fully synced from Fortnox, so the
-- background refresh knows whether the data is stale.
CREATE TABLE IF NOT EXISTS public.fortnox_cache_meta (
  workshop_id uuid NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('customers','articles')),
  synced_at   timestamptz,
  PRIMARY KEY (workshop_id, kind)
);

-- All access is server-side via the service role (which bypasses RLS). Enable
-- RLS with no permissive policies so the cache is never readable cross-tenant
-- through the anon/authenticated keys.
ALTER TABLE public.fortnox_customers_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fortnox_articles_cache  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fortnox_cache_meta      ENABLE ROW LEVEL SECURITY;


-- ------------------------------------------------------------
-- File: 20260626160000_invoice_pdf_column.sql
-- ------------------------------------------------------------

-- Store the rendered invoice PDF (base64) on the job so it can be reopened
-- instantly without re-fetching from Fortnox.
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS invoice_pdf_base64 text;


-- ------------------------------------------------------------
-- File: 20260629000000_customer_name_split.sql
-- ------------------------------------------------------------

-- Split customer_name into customer_first_name + customer_last_name.
-- customer_name is kept in sync as the concatenated display name.

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS customer_first_name TEXT,
  ADD COLUMN IF NOT EXISTS customer_last_name  TEXT;

-- Backfill from existing customer_name
UPDATE public.jobs
SET
  customer_first_name = TRIM(SPLIT_PART(customer_name, ' ', 1)),
  customer_last_name  = TRIM(SUBSTRING(customer_name FROM POSITION(' ' IN customer_name) + 1))
WHERE customer_first_name IS NULL;

-- For single-word names, customer_last_name should be empty string → NULL
UPDATE public.jobs
SET customer_last_name = NULL
WHERE customer_last_name = '' OR customer_last_name = customer_name;


-- ------------------------------------------------------------
-- File: 20260629010000_job_fortnox_customer_number.sql
-- ------------------------------------------------------------

-- Store the Fortnox customer number directly on the job at creation time.
-- This lets the invoice generation step use the pre-linked customer instead
-- of having to search/create one again.
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS fortnox_customer_number TEXT;


-- ------------------------------------------------------------
-- File: 20260630120000_fortnox_refresh_lock.sql
-- ------------------------------------------------------------

-- Fortnox rotates the refresh_token on every use and immediately invalidates the
-- previous one. In a serverless environment, concurrent requests run in separate
-- processes that can each read the same stale refresh_token and race to use it —
-- the loser gets invalid_grant, which previously surfaced as "Fortnox-anslutningen
-- har upphört att gälla" and required a full manual reconnect even though the
-- connection itself was fine. This column lets refreshAccessTokenForUser claim an
-- exclusive cross-process lock (via an atomic UPDATE ... WHERE) before calling
-- Fortnox, so only one process ever rotates the token at a time; others wait and
-- read back the winner's result instead of racing.
ALTER TABLE public.fortnox_connections
  ADD COLUMN IF NOT EXISTS refreshing_at timestamptz;


-- ------------------------------------------------------------
-- File: 20260630130000_customer_company_name.sql
-- ------------------------------------------------------------

-- Optional company name for a job's customer. When set, this is the
-- official/Fortnox-facing name (customer_name resolves to this value);
-- when empty, customer_name falls back to the personal first/last name.

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS customer_company_name TEXT;


-- ------------------------------------------------------------
-- File: 20260701120000_invoice_bookkept_at.sql
-- ------------------------------------------------------------

-- Track when an invoice was actually bookkept in Fortnox, distinct from
-- invoice_booked_at (which is set for every finalize action — book, send,
-- or book_send — regardless of whether bookkeeping actually happened).
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS invoice_bookkept_at timestamptz;


-- ------------------------------------------------------------
-- File: 20260702090000_fortnox_refresh_events.sql
-- ------------------------------------------------------------

-- Persistent audit trail for Fortnox token refreshes.
--
-- Fortnox rotates the refresh_token on every use and immediately invalidates
-- the previous one. If the serverless process is killed between Fortnox
-- rotating the token and us persisting the new one (e.g. the Netlify function
-- timeout fires mid-request), the connection is permanently wedged — and a
-- dead process can never write a console log, so Netlify function logs cannot
-- capture this failure mode at all. This table can: a row is inserted BEFORE
-- the token call and updated after it finishes, so a row whose finished_at is
-- NULL means the process died mid-rotation. Rows survive Netlify's short log
-- retention and are queryable long after the fact.
CREATE TABLE IF NOT EXISTS public.fortnox_refresh_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  -- what caused the refresh: 'expiry-buffer' (proactive) or '401-retry'
  trigger_reason text NOT NULL,
  attempt integer NOT NULL DEFAULT 0,
  -- sha256 prefix of the refresh_token used, to prove WHICH token was spent
  token_fingerprint text,
  -- expires_at of the connection before this refresh ran
  old_expires_at timestamptz,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  -- 'success' | 'token-error' (Fortnox rejected/failed the token call)
  -- | 'store-error' (Fortnox rotated the token but the DB write failed — the
  --   dangerous wedge case). NULL with finished_at NULL = process died mid-flight.
  outcome text,
  error_status integer,
  error_body text,
  duration_ms integer
);

-- Server-only table: RLS enabled with no policies, so only the service role
-- (which bypasses RLS) can read or write it.
ALTER TABLE public.fortnox_refresh_events ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS fortnox_refresh_events_user_started_idx
  ON public.fortnox_refresh_events (user_id, started_at DESC);


-- ------------------------------------------------------------
-- File: 20260702153000_fortnox_refresh_cron.sql
-- ------------------------------------------------------------

-- Schedules the fortnox-refresh Edge Function to run every 5 minutes, so
-- Fortnox token rotation happens on a background timer instead of inline
-- during a live user request. See supabase/functions/fortnox-refresh/index.ts
-- for why: a live-request refresh can be frozen/killed by the serverless
-- runtime after Fortnox has already rotated the token but before we saved
-- it, permanently wedging the connection — confirmed in production on
-- 2026-07-02 via the fortnox_refresh_events audit trail.
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- The shared secret the cron job sends (as `x-cron-secret`) so the Edge
-- Function can verify the call actually came from our own pg_cron and not an
-- arbitrary internet request. The secret's VALUE is intentionally not in this
-- file — it lives in Supabase Vault (`select vault.create_secret(...)`, run
-- once directly against the project, not checked into git) under the name
-- 'fortnox_cron_secret', and must match the Edge Function's CRON_SECRET
-- secret (`supabase secrets set CRON_SECRET=...`). Setting up a new
-- environment requires creating both by hand.
SELECT cron.schedule(
  'fortnox-token-refresh',
  '*/5 * * * *',
  $$
  SELECT net.http_post(
    url := 'https://YOUR_PROJECT_REF.supabase.co/functions/v1/fortnox-refresh',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'fortnox_cron_secret' LIMIT 1)
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 20000
  );
  $$
);


-- ------------------------------------------------------------
-- File: 20260703120000_welcome_sms_and_quote_notifications.sql
-- ------------------------------------------------------------

-- Two related notification/SMS improvements.
--
-- 1) link_sms_sent_at on jobs: tracks when the introductory "here is your
--    link / how to log in" SMS was sent to the customer. The very first
--    outbound SMS on a job must always be this welcome message, so later
--    status/quote/chat SMS check this column and send the welcome first when
--    it hasn't gone out yet (e.g. the workshop added the phone number only
--    when sending a quote). Existing jobs are backfilled to created_at so
--    customers already mid-flow don't receive a fresh welcome SMS.
--
-- 2) notify_quote_responses on profiles: workshop-level toggle for the push
--    notification sent to every account in the workshop when a customer
--    approves (or rejects) a quote. Defaults on.

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS link_sms_sent_at timestamptz;

UPDATE public.jobs
  SET link_sms_sent_at = created_at
  WHERE link_sms_sent_at IS NULL;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS notify_quote_responses boolean NOT NULL DEFAULT true;


-- ------------------------------------------------------------
-- File: 20260707200000_invoice_snapshot.sql
-- ------------------------------------------------------------

-- Frozen snapshot of everything the invoice PDF render needs, captured once
-- when the invoice is booked/sent: the full Fortnox invoice as it existed at
-- that moment plus the workshop's company details (name, address, bank
-- details, logo). Opening the invoice later re-renders from this snapshot —
-- same pipeline as "Förhandsgranska" — so the customer always sees the
-- document as issued, no matter how profile data or render code change later.
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS invoice_snapshot jsonb;


-- ------------------------------------------------------------
-- File: 20260707210000_client_diagnostics.sql
-- ------------------------------------------------------------

-- Temporary diagnostics sink for the open-invoice investigation: the failure
-- reloads the page on the phone, destroying any client-side evidence, so each
-- step is beaconed to the server and stored here. Read via
-- /api/public/client-log?key=... . Drop the table when the bug is fixed.
CREATE TABLE IF NOT EXISTS public.client_diagnostics (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  session text,
  step text NOT NULL,
  detail text
);
-- Service-role access only (no policies on purpose).
ALTER TABLE public.client_diagnostics ENABLE ROW LEVEL SECURITY;
