/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerkstadRouteImport } from './routes/verkstad'
import { Route as VarukorgRouteImport } from './routes/varukorg'
import { Route as ProdukterRouteImport } from './routes/produkter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerkstadIndexRouteImport } from './routes/verkstad.index'
import { Route as BestallningarIndexRouteImport } from './routes/bestallningar.index'
import { Route as VerkstadStatistikRouteImport } from './routes/verkstad.statistik'
import { Route as VerkstadInstallningarRouteImport } from './routes/verkstad.installningar'
import { Route as VerkstadChattRouteImport } from './routes/verkstad.chatt'
import { Route as ProduktIdRouteImport } from './routes/produkt.$id'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as BestallningarIdRouteImport } from './routes/bestallningar.$id'
import { Route as BTokenRouteImport } from './routes/b.$token'
import { Route as ApiPushTestRouteImport } from './routes/api/push-test'
import { Route as ApiGmailDiagnosticRouteImport } from './routes/api/gmail-diagnostic'
import { Route as ApiFortnoxPaymentTermsDiagnosticRouteImport } from './routes/api/fortnox-payment-terms-diagnostic'
import { Route as ApiFortnoxArticleCleanupRouteImport } from './routes/api/fortnox-article-cleanup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScandicRouteImport } from './routes/_authenticated/scandic'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedNewJobRouteImport } from './routes/_authenticated/new-job'
import { Route as AuthenticatedManageUsersRouteImport } from './routes/_authenticated/manage-users'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedArchivedRouteImport } from './routes/_authenticated/archived'
import { Route as ScandicBookTokenRouteImport } from './routes/scandic.book.$token'
import { Route as ApiPublicInvoicePdfRouteImport } from './routes/api/public/invoice-pdf'
import { Route as ApiPublicClientLogRouteImport } from './routes/api/public/client-log'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as CTokenUpdatesUpdateIdRouteImport } from './routes/c.$token.updates.$updateId'
import { Route as ApiPublicVismaCallbackRouteImport } from './routes/api/public/visma.callback'
import { Route as ApiPublicHooksVismaRunInvoicesRouteImport } from './routes/api/public/hooks/visma-run-invoices'
import { Route as ApiPublicHooksSendDueOpportunitiesRouteImport } from './routes/api/public/hooks/send-due-opportunities'
import { Route as ApiPublicHooksScandicRemindersRouteImport } from './routes/api/public/hooks/scandic-reminders'
import { Route as ApiPublicHooksPushRemindersRouteImport } from './routes/api/public/hooks/push-reminders'
import { Route as ApiPublicHooksElksIncomingRouteImport } from './routes/api/public/hooks/elks-incoming'
import { Route as ApiPublicHooksChatRemindersRouteImport } from './routes/api/public/hooks/chat-reminders'
import { Route as ApiPublicFortnoxCallbackRouteImport } from './routes/api/public/fortnox.callback'
import { Route as AuthenticatedJobsIdInvoiceRouteImport } from './routes/_authenticated/jobs.$id.invoice'
import { Route as AuthenticatedJobsIdUpdatesUpdateIdRouteImport } from './routes/_authenticated/jobs.$id.updates.$updateId'

const VerkstadRoute = VerkstadRouteImport.update({
  id: '/verkstad',
  path: '/verkstad',
  getParentRoute: () => rootRouteImport,
} as any)
const VarukorgRoute = VarukorgRouteImport.update({
  id: '/varukorg',
  path: '/varukorg',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterRoute = ProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerkstadIndexRoute = VerkstadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerkstadRoute,
} as any)
const BestallningarIndexRoute = BestallningarIndexRouteImport.update({
  id: '/bestallningar/',
  path: '/bestallningar/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerkstadStatistikRoute = VerkstadStatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => VerkstadRoute,
} as any)
const VerkstadInstallningarRoute = VerkstadInstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => VerkstadRoute,
} as any)
const VerkstadChattRoute = VerkstadChattRouteImport.update({
  id: '/chatt',
  path: '/chatt',
  getParentRoute: () => VerkstadRoute,
} as any)
const ProduktIdRoute = ProduktIdRouteImport.update({
  id: '/produkt/$id',
  path: '/produkt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BestallningarIdRoute = BestallningarIdRouteImport.update({
  id: '/bestallningar/$id',
  path: '/bestallningar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BTokenRoute = BTokenRouteImport.update({
  id: '/b/$token',
  path: '/b/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/api/push-test',
  path: '/api/push-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailDiagnosticRoute = ApiGmailDiagnosticRouteImport.update({
  id: '/api/gmail-diagnostic',
  path: '/api/gmail-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFortnoxPaymentTermsDiagnosticRoute =
  ApiFortnoxPaymentTermsDiagnosticRouteImport.update({
    id: '/api/fortnox-payment-terms-diagnostic',
    path: '/api/fortnox-payment-terms-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFortnoxArticleCleanupRoute =
  ApiFortnoxArticleCleanupRouteImport.update({
    id: '/api/fortnox-article-cleanup',
    path: '/api/fortnox-article-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScandicRoute = AuthenticatedScandicRouteImport.update({
  id: '/scandic',
  path: '/scandic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNewJobRoute = AuthenticatedNewJobRouteImport.update({
  id: '/new-job',
  path: '/new-job',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManageUsersRoute =
  AuthenticatedManageUsersRouteImport.update({
    id: '/manage-users',
    path: '/manage-users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchivedRoute = AuthenticatedArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ScandicBookTokenRoute = ScandicBookTokenRouteImport.update({
  id: '/scandic/book/$token',
  path: '/scandic/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInvoicePdfRoute = ApiPublicInvoicePdfRouteImport.update({
  id: '/api/public/invoice-pdf',
  path: '/api/public/invoice-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientLogRoute = ApiPublicClientLogRouteImport.update({
  id: '/api/public/client-log',
  path: '/api/public/client-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CTokenUpdatesUpdateIdRoute = CTokenUpdatesUpdateIdRouteImport.update({
  id: '/updates/$updateId',
  path: '/updates/$updateId',
  getParentRoute: () => CTokenRoute,
} as any)
const ApiPublicVismaCallbackRoute = ApiPublicVismaCallbackRouteImport.update({
  id: '/api/public/visma/callback',
  path: '/api/public/visma/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVismaRunInvoicesRoute =
  ApiPublicHooksVismaRunInvoicesRouteImport.update({
    id: '/api/public/hooks/visma-run-invoices',
    path: '/api/public/hooks/visma-run-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendDueOpportunitiesRoute =
  ApiPublicHooksSendDueOpportunitiesRouteImport.update({
    id: '/api/public/hooks/send-due-opportunities',
    path: '/api/public/hooks/send-due-opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScandicRemindersRoute =
  ApiPublicHooksScandicRemindersRouteImport.update({
    id: '/api/public/hooks/scandic-reminders',
    path: '/api/public/hooks/scandic-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPushRemindersRoute =
  ApiPublicHooksPushRemindersRouteImport.update({
    id: '/api/public/hooks/push-reminders',
    path: '/api/public/hooks/push-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksElksIncomingRoute =
  ApiPublicHooksElksIncomingRouteImport.update({
    id: '/api/public/hooks/elks-incoming',
    path: '/api/public/hooks/elks-incoming',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksChatRemindersRoute =
  ApiPublicHooksChatRemindersRouteImport.update({
    id: '/api/public/hooks/chat-reminders',
    path: '/api/public/hooks/chat-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFortnoxCallbackRoute =
  ApiPublicFortnoxCallbackRouteImport.update({
    id: '/api/public/fortnox/callback',
    path: '/api/public/fortnox/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedJobsIdInvoiceRoute =
  AuthenticatedJobsIdInvoiceRouteImport.update({
    id: '/invoice',
    path: '/invoice',
    getParentRoute: () => AuthenticatedJobsIdRoute,
  } as any)
const AuthenticatedJobsIdUpdatesUpdateIdRoute =
  AuthenticatedJobsIdUpdatesUpdateIdRouteImport.update({
    id: '/updates/$updateId',
    path: '/updates/$updateId',
    getParentRoute: () => AuthenticatedJobsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/produkter': typeof ProdukterRoute
  '/varukorg': typeof VarukorgRoute
  '/verkstad': typeof VerkstadRouteWithChildren
  '/archived': typeof AuthenticatedArchivedRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/manage-users': typeof AuthenticatedManageUsersRoute
  '/new-job': typeof AuthenticatedNewJobRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/scandic': typeof AuthenticatedScandicRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/fortnox-article-cleanup': typeof ApiFortnoxArticleCleanupRoute
  '/api/fortnox-payment-terms-diagnostic': typeof ApiFortnoxPaymentTermsDiagnosticRoute
  '/api/gmail-diagnostic': typeof ApiGmailDiagnosticRoute
  '/api/push-test': typeof ApiPushTestRoute
  '/b/$token': typeof BTokenRoute
  '/bestallningar/$id': typeof BestallningarIdRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/produkt/$id': typeof ProduktIdRoute
  '/verkstad/chatt': typeof VerkstadChattRoute
  '/verkstad/installningar': typeof VerkstadInstallningarRoute
  '/verkstad/statistik': typeof VerkstadStatistikRoute
  '/bestallningar/': typeof BestallningarIndexRoute
  '/verkstad/': typeof VerkstadIndexRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/api/public/client-log': typeof ApiPublicClientLogRoute
  '/api/public/invoice-pdf': typeof ApiPublicInvoicePdfRoute
  '/scandic/book/$token': typeof ScandicBookTokenRoute
  '/jobs/$id/invoice': typeof AuthenticatedJobsIdInvoiceRoute
  '/api/public/fortnox/callback': typeof ApiPublicFortnoxCallbackRoute
  '/api/public/hooks/chat-reminders': typeof ApiPublicHooksChatRemindersRoute
  '/api/public/hooks/elks-incoming': typeof ApiPublicHooksElksIncomingRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
  '/api/public/hooks/scandic-reminders': typeof ApiPublicHooksScandicRemindersRoute
  '/api/public/hooks/send-due-opportunities': typeof ApiPublicHooksSendDueOpportunitiesRoute
  '/api/public/hooks/visma-run-invoices': typeof ApiPublicHooksVismaRunInvoicesRoute
  '/api/public/visma/callback': typeof ApiPublicVismaCallbackRoute
  '/c/$token/updates/$updateId': typeof CTokenUpdatesUpdateIdRoute
  '/jobs/$id/updates/$updateId': typeof AuthenticatedJobsIdUpdatesUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/produkter': typeof ProdukterRoute
  '/varukorg': typeof VarukorgRoute
  '/archived': typeof AuthenticatedArchivedRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/manage-users': typeof AuthenticatedManageUsersRoute
  '/new-job': typeof AuthenticatedNewJobRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/scandic': typeof AuthenticatedScandicRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/fortnox-article-cleanup': typeof ApiFortnoxArticleCleanupRoute
  '/api/fortnox-payment-terms-diagnostic': typeof ApiFortnoxPaymentTermsDiagnosticRoute
  '/api/gmail-diagnostic': typeof ApiGmailDiagnosticRoute
  '/api/push-test': typeof ApiPushTestRoute
  '/b/$token': typeof BTokenRoute
  '/bestallningar/$id': typeof BestallningarIdRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/produkt/$id': typeof ProduktIdRoute
  '/verkstad/chatt': typeof VerkstadChattRoute
  '/verkstad/installningar': typeof VerkstadInstallningarRoute
  '/verkstad/statistik': typeof VerkstadStatistikRoute
  '/bestallningar': typeof BestallningarIndexRoute
  '/verkstad': typeof VerkstadIndexRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/api/public/client-log': typeof ApiPublicClientLogRoute
  '/api/public/invoice-pdf': typeof ApiPublicInvoicePdfRoute
  '/scandic/book/$token': typeof ScandicBookTokenRoute
  '/jobs/$id/invoice': typeof AuthenticatedJobsIdInvoiceRoute
  '/api/public/fortnox/callback': typeof ApiPublicFortnoxCallbackRoute
  '/api/public/hooks/chat-reminders': typeof ApiPublicHooksChatRemindersRoute
  '/api/public/hooks/elks-incoming': typeof ApiPublicHooksElksIncomingRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
  '/api/public/hooks/scandic-reminders': typeof ApiPublicHooksScandicRemindersRoute
  '/api/public/hooks/send-due-opportunities': typeof ApiPublicHooksSendDueOpportunitiesRoute
  '/api/public/hooks/visma-run-invoices': typeof ApiPublicHooksVismaRunInvoicesRoute
  '/api/public/visma/callback': typeof ApiPublicVismaCallbackRoute
  '/c/$token/updates/$updateId': typeof CTokenUpdatesUpdateIdRoute
  '/jobs/$id/updates/$updateId': typeof AuthenticatedJobsIdUpdatesUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/produkter': typeof ProdukterRoute
  '/varukorg': typeof VarukorgRoute
  '/verkstad': typeof VerkstadRouteWithChildren
  '/_authenticated/archived': typeof AuthenticatedArchivedRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/manage-users': typeof AuthenticatedManageUsersRoute
  '/_authenticated/new-job': typeof AuthenticatedNewJobRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/scandic': typeof AuthenticatedScandicRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/fortnox-article-cleanup': typeof ApiFortnoxArticleCleanupRoute
  '/api/fortnox-payment-terms-diagnostic': typeof ApiFortnoxPaymentTermsDiagnosticRoute
  '/api/gmail-diagnostic': typeof ApiGmailDiagnosticRoute
  '/api/push-test': typeof ApiPushTestRoute
  '/b/$token': typeof BTokenRoute
  '/bestallningar/$id': typeof BestallningarIdRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/produkt/$id': typeof ProduktIdRoute
  '/verkstad/chatt': typeof VerkstadChattRoute
  '/verkstad/installningar': typeof VerkstadInstallningarRoute
  '/verkstad/statistik': typeof VerkstadStatistikRoute
  '/bestallningar/': typeof BestallningarIndexRoute
  '/verkstad/': typeof VerkstadIndexRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/api/public/client-log': typeof ApiPublicClientLogRoute
  '/api/public/invoice-pdf': typeof ApiPublicInvoicePdfRoute
  '/scandic/book/$token': typeof ScandicBookTokenRoute
  '/_authenticated/jobs/$id/invoice': typeof AuthenticatedJobsIdInvoiceRoute
  '/api/public/fortnox/callback': typeof ApiPublicFortnoxCallbackRoute
  '/api/public/hooks/chat-reminders': typeof ApiPublicHooksChatRemindersRoute
  '/api/public/hooks/elks-incoming': typeof ApiPublicHooksElksIncomingRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
  '/api/public/hooks/scandic-reminders': typeof ApiPublicHooksScandicRemindersRoute
  '/api/public/hooks/send-due-opportunities': typeof ApiPublicHooksSendDueOpportunitiesRoute
  '/api/public/hooks/visma-run-invoices': typeof ApiPublicHooksVismaRunInvoicesRoute
  '/api/public/visma/callback': typeof ApiPublicVismaCallbackRoute
  '/c/$token/updates/$updateId': typeof CTokenUpdatesUpdateIdRoute
  '/_authenticated/jobs/$id/updates/$updateId': typeof AuthenticatedJobsIdUpdatesUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/konto'
    | '/login'
    | '/produkter'
    | '/varukorg'
    | '/verkstad'
    | '/archived'
    | '/campaigns'
    | '/customers'
    | '/dashboard'
    | '/insights'
    | '/manage-users'
    | '/new-job'
    | '/opportunities'
    | '/scandic'
    | '/settings'
    | '/api/fortnox-article-cleanup'
    | '/api/fortnox-payment-terms-diagnostic'
    | '/api/gmail-diagnostic'
    | '/api/push-test'
    | '/b/$token'
    | '/bestallningar/$id'
    | '/c/$token'
    | '/produkt/$id'
    | '/verkstad/chatt'
    | '/verkstad/installningar'
    | '/verkstad/statistik'
    | '/bestallningar/'
    | '/verkstad/'
    | '/jobs/$id'
    | '/api/public/client-log'
    | '/api/public/invoice-pdf'
    | '/scandic/book/$token'
    | '/jobs/$id/invoice'
    | '/api/public/fortnox/callback'
    | '/api/public/hooks/chat-reminders'
    | '/api/public/hooks/elks-incoming'
    | '/api/public/hooks/push-reminders'
    | '/api/public/hooks/scandic-reminders'
    | '/api/public/hooks/send-due-opportunities'
    | '/api/public/hooks/visma-run-invoices'
    | '/api/public/visma/callback'
    | '/c/$token/updates/$updateId'
    | '/jobs/$id/updates/$updateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/konto'
    | '/login'
    | '/produkter'
    | '/varukorg'
    | '/archived'
    | '/campaigns'
    | '/customers'
    | '/dashboard'
    | '/insights'
    | '/manage-users'
    | '/new-job'
    | '/opportunities'
    | '/scandic'
    | '/settings'
    | '/api/fortnox-article-cleanup'
    | '/api/fortnox-payment-terms-diagnostic'
    | '/api/gmail-diagnostic'
    | '/api/push-test'
    | '/b/$token'
    | '/bestallningar/$id'
    | '/c/$token'
    | '/produkt/$id'
    | '/verkstad/chatt'
    | '/verkstad/installningar'
    | '/verkstad/statistik'
    | '/bestallningar'
    | '/verkstad'
    | '/jobs/$id'
    | '/api/public/client-log'
    | '/api/public/invoice-pdf'
    | '/scandic/book/$token'
    | '/jobs/$id/invoice'
    | '/api/public/fortnox/callback'
    | '/api/public/hooks/chat-reminders'
    | '/api/public/hooks/elks-incoming'
    | '/api/public/hooks/push-reminders'
    | '/api/public/hooks/scandic-reminders'
    | '/api/public/hooks/send-due-opportunities'
    | '/api/public/hooks/visma-run-invoices'
    | '/api/public/visma/callback'
    | '/c/$token/updates/$updateId'
    | '/jobs/$id/updates/$updateId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/konto'
    | '/login'
    | '/produkter'
    | '/varukorg'
    | '/verkstad'
    | '/_authenticated/archived'
    | '/_authenticated/campaigns'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/manage-users'
    | '/_authenticated/new-job'
    | '/_authenticated/opportunities'
    | '/_authenticated/scandic'
    | '/_authenticated/settings'
    | '/api/fortnox-article-cleanup'
    | '/api/fortnox-payment-terms-diagnostic'
    | '/api/gmail-diagnostic'
    | '/api/push-test'
    | '/b/$token'
    | '/bestallningar/$id'
    | '/c/$token'
    | '/produkt/$id'
    | '/verkstad/chatt'
    | '/verkstad/installningar'
    | '/verkstad/statistik'
    | '/bestallningar/'
    | '/verkstad/'
    | '/_authenticated/jobs/$id'
    | '/api/public/client-log'
    | '/api/public/invoice-pdf'
    | '/scandic/book/$token'
    | '/_authenticated/jobs/$id/invoice'
    | '/api/public/fortnox/callback'
    | '/api/public/hooks/chat-reminders'
    | '/api/public/hooks/elks-incoming'
    | '/api/public/hooks/push-reminders'
    | '/api/public/hooks/scandic-reminders'
    | '/api/public/hooks/send-due-opportunities'
    | '/api/public/hooks/visma-run-invoices'
    | '/api/public/visma/callback'
    | '/c/$token/updates/$updateId'
    | '/_authenticated/jobs/$id/updates/$updateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  KontoRoute: typeof KontoRoute
  LoginRoute: typeof LoginRoute
  ProdukterRoute: typeof ProdukterRoute
  VarukorgRoute: typeof VarukorgRoute
  VerkstadRoute: typeof VerkstadRouteWithChildren
  ApiFortnoxArticleCleanupRoute: typeof ApiFortnoxArticleCleanupRoute
  ApiFortnoxPaymentTermsDiagnosticRoute: typeof ApiFortnoxPaymentTermsDiagnosticRoute
  ApiGmailDiagnosticRoute: typeof ApiGmailDiagnosticRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
  BTokenRoute: typeof BTokenRoute
  BestallningarIdRoute: typeof BestallningarIdRoute
  CTokenRoute: typeof CTokenRouteWithChildren
  ProduktIdRoute: typeof ProduktIdRoute
  BestallningarIndexRoute: typeof BestallningarIndexRoute
  ApiPublicClientLogRoute: typeof ApiPublicClientLogRoute
  ApiPublicInvoicePdfRoute: typeof ApiPublicInvoicePdfRoute
  ScandicBookTokenRoute: typeof ScandicBookTokenRoute
  ApiPublicFortnoxCallbackRoute: typeof ApiPublicFortnoxCallbackRoute
  ApiPublicHooksChatRemindersRoute: typeof ApiPublicHooksChatRemindersRoute
  ApiPublicHooksElksIncomingRoute: typeof ApiPublicHooksElksIncomingRoute
  ApiPublicHooksPushRemindersRoute: typeof ApiPublicHooksPushRemindersRoute
  ApiPublicHooksScandicRemindersRoute: typeof ApiPublicHooksScandicRemindersRoute
  ApiPublicHooksSendDueOpportunitiesRoute: typeof ApiPublicHooksSendDueOpportunitiesRoute
  ApiPublicHooksVismaRunInvoicesRoute: typeof ApiPublicHooksVismaRunInvoicesRoute
  ApiPublicVismaCallbackRoute: typeof ApiPublicVismaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verkstad': {
      id: '/verkstad'
      path: '/verkstad'
      fullPath: '/verkstad'
      preLoaderRoute: typeof VerkstadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varukorg': {
      id: '/varukorg'
      path: '/varukorg'
      fullPath: '/varukorg'
      preLoaderRoute: typeof VarukorgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter': {
      id: '/produkter'
      path: '/produkter'
      fullPath: '/produkter'
      preLoaderRoute: typeof ProdukterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verkstad/': {
      id: '/verkstad/'
      path: '/'
      fullPath: '/verkstad/'
      preLoaderRoute: typeof VerkstadIndexRouteImport
      parentRoute: typeof VerkstadRoute
    }
    '/bestallningar/': {
      id: '/bestallningar/'
      path: '/bestallningar'
      fullPath: '/bestallningar/'
      preLoaderRoute: typeof BestallningarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verkstad/statistik': {
      id: '/verkstad/statistik'
      path: '/statistik'
      fullPath: '/verkstad/statistik'
      preLoaderRoute: typeof VerkstadStatistikRouteImport
      parentRoute: typeof VerkstadRoute
    }
    '/verkstad/installningar': {
      id: '/verkstad/installningar'
      path: '/installningar'
      fullPath: '/verkstad/installningar'
      preLoaderRoute: typeof VerkstadInstallningarRouteImport
      parentRoute: typeof VerkstadRoute
    }
    '/verkstad/chatt': {
      id: '/verkstad/chatt'
      path: '/chatt'
      fullPath: '/verkstad/chatt'
      preLoaderRoute: typeof VerkstadChattRouteImport
      parentRoute: typeof VerkstadRoute
    }
    '/produkt/$id': {
      id: '/produkt/$id'
      path: '/produkt/$id'
      fullPath: '/produkt/$id'
      preLoaderRoute: typeof ProduktIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestallningar/$id': {
      id: '/bestallningar/$id'
      path: '/bestallningar/$id'
      fullPath: '/bestallningar/$id'
      preLoaderRoute: typeof BestallningarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$token': {
      id: '/b/$token'
      path: '/b/$token'
      fullPath: '/b/$token'
      preLoaderRoute: typeof BTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-test': {
      id: '/api/push-test'
      path: '/api/push-test'
      fullPath: '/api/push-test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-diagnostic': {
      id: '/api/gmail-diagnostic'
      path: '/api/gmail-diagnostic'
      fullPath: '/api/gmail-diagnostic'
      preLoaderRoute: typeof ApiGmailDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fortnox-payment-terms-diagnostic': {
      id: '/api/fortnox-payment-terms-diagnostic'
      path: '/api/fortnox-payment-terms-diagnostic'
      fullPath: '/api/fortnox-payment-terms-diagnostic'
      preLoaderRoute: typeof ApiFortnoxPaymentTermsDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fortnox-article-cleanup': {
      id: '/api/fortnox-article-cleanup'
      path: '/api/fortnox-article-cleanup'
      fullPath: '/api/fortnox-article-cleanup'
      preLoaderRoute: typeof ApiFortnoxArticleCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scandic': {
      id: '/_authenticated/scandic'
      path: '/scandic'
      fullPath: '/scandic'
      preLoaderRoute: typeof AuthenticatedScandicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-job': {
      id: '/_authenticated/new-job'
      path: '/new-job'
      fullPath: '/new-job'
      preLoaderRoute: typeof AuthenticatedNewJobRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage-users': {
      id: '/_authenticated/manage-users'
      path: '/manage-users'
      fullPath: '/manage-users'
      preLoaderRoute: typeof AuthenticatedManageUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archived': {
      id: '/_authenticated/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof AuthenticatedArchivedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/scandic/book/$token': {
      id: '/scandic/book/$token'
      path: '/scandic/book/$token'
      fullPath: '/scandic/book/$token'
      preLoaderRoute: typeof ScandicBookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/invoice-pdf': {
      id: '/api/public/invoice-pdf'
      path: '/api/public/invoice-pdf'
      fullPath: '/api/public/invoice-pdf'
      preLoaderRoute: typeof ApiPublicInvoicePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-log': {
      id: '/api/public/client-log'
      path: '/api/public/client-log'
      fullPath: '/api/public/client-log'
      preLoaderRoute: typeof ApiPublicClientLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/c/$token/updates/$updateId': {
      id: '/c/$token/updates/$updateId'
      path: '/updates/$updateId'
      fullPath: '/c/$token/updates/$updateId'
      preLoaderRoute: typeof CTokenUpdatesUpdateIdRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/api/public/visma/callback': {
      id: '/api/public/visma/callback'
      path: '/api/public/visma/callback'
      fullPath: '/api/public/visma/callback'
      preLoaderRoute: typeof ApiPublicVismaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/visma-run-invoices': {
      id: '/api/public/hooks/visma-run-invoices'
      path: '/api/public/hooks/visma-run-invoices'
      fullPath: '/api/public/hooks/visma-run-invoices'
      preLoaderRoute: typeof ApiPublicHooksVismaRunInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-due-opportunities': {
      id: '/api/public/hooks/send-due-opportunities'
      path: '/api/public/hooks/send-due-opportunities'
      fullPath: '/api/public/hooks/send-due-opportunities'
      preLoaderRoute: typeof ApiPublicHooksSendDueOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scandic-reminders': {
      id: '/api/public/hooks/scandic-reminders'
      path: '/api/public/hooks/scandic-reminders'
      fullPath: '/api/public/hooks/scandic-reminders'
      preLoaderRoute: typeof ApiPublicHooksScandicRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-reminders': {
      id: '/api/public/hooks/push-reminders'
      path: '/api/public/hooks/push-reminders'
      fullPath: '/api/public/hooks/push-reminders'
      preLoaderRoute: typeof ApiPublicHooksPushRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/elks-incoming': {
      id: '/api/public/hooks/elks-incoming'
      path: '/api/public/hooks/elks-incoming'
      fullPath: '/api/public/hooks/elks-incoming'
      preLoaderRoute: typeof ApiPublicHooksElksIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/chat-reminders': {
      id: '/api/public/hooks/chat-reminders'
      path: '/api/public/hooks/chat-reminders'
      fullPath: '/api/public/hooks/chat-reminders'
      preLoaderRoute: typeof ApiPublicHooksChatRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fortnox/callback': {
      id: '/api/public/fortnox/callback'
      path: '/api/public/fortnox/callback'
      fullPath: '/api/public/fortnox/callback'
      preLoaderRoute: typeof ApiPublicFortnoxCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs/$id/invoice': {
      id: '/_authenticated/jobs/$id/invoice'
      path: '/invoice'
      fullPath: '/jobs/$id/invoice'
      preLoaderRoute: typeof AuthenticatedJobsIdInvoiceRouteImport
      parentRoute: typeof AuthenticatedJobsIdRoute
    }
    '/_authenticated/jobs/$id/updates/$updateId': {
      id: '/_authenticated/jobs/$id/updates/$updateId'
      path: '/updates/$updateId'
      fullPath: '/jobs/$id/updates/$updateId'
      preLoaderRoute: typeof AuthenticatedJobsIdUpdatesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedJobsIdRoute
    }
  }
}

interface AuthenticatedJobsIdRouteChildren {
  AuthenticatedJobsIdInvoiceRoute: typeof AuthenticatedJobsIdInvoiceRoute
  AuthenticatedJobsIdUpdatesUpdateIdRoute: typeof AuthenticatedJobsIdUpdatesUpdateIdRoute
}

const AuthenticatedJobsIdRouteChildren: AuthenticatedJobsIdRouteChildren = {
  AuthenticatedJobsIdInvoiceRoute: AuthenticatedJobsIdInvoiceRoute,
  AuthenticatedJobsIdUpdatesUpdateIdRoute:
    AuthenticatedJobsIdUpdatesUpdateIdRoute,
}

const AuthenticatedJobsIdRouteWithChildren =
  AuthenticatedJobsIdRoute._addFileChildren(AuthenticatedJobsIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedArchivedRoute: typeof AuthenticatedArchivedRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedManageUsersRoute: typeof AuthenticatedManageUsersRoute
  AuthenticatedNewJobRoute: typeof AuthenticatedNewJobRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedScandicRoute: typeof AuthenticatedScandicRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArchivedRoute: AuthenticatedArchivedRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedManageUsersRoute: AuthenticatedManageUsersRoute,
  AuthenticatedNewJobRoute: AuthenticatedNewJobRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedScandicRoute: AuthenticatedScandicRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface VerkstadRouteChildren {
  VerkstadChattRoute: typeof VerkstadChattRoute
  VerkstadInstallningarRoute: typeof VerkstadInstallningarRoute
  VerkstadStatistikRoute: typeof VerkstadStatistikRoute
  VerkstadIndexRoute: typeof VerkstadIndexRoute
}

const VerkstadRouteChildren: VerkstadRouteChildren = {
  VerkstadChattRoute: VerkstadChattRoute,
  VerkstadInstallningarRoute: VerkstadInstallningarRoute,
  VerkstadStatistikRoute: VerkstadStatistikRoute,
  VerkstadIndexRoute: VerkstadIndexRoute,
}

const VerkstadRouteWithChildren = VerkstadRoute._addFileChildren(
  VerkstadRouteChildren,
)

interface CTokenRouteChildren {
  CTokenUpdatesUpdateIdRoute: typeof CTokenUpdatesUpdateIdRoute
}

const CTokenRouteChildren: CTokenRouteChildren = {
  CTokenUpdatesUpdateIdRoute: CTokenUpdatesUpdateIdRoute,
}

const CTokenRouteWithChildren =
  CTokenRoute._addFileChildren(CTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  KontoRoute: KontoRoute,
  LoginRoute: LoginRoute,
  ProdukterRoute: ProdukterRoute,
  VarukorgRoute: VarukorgRoute,
  VerkstadRoute: VerkstadRouteWithChildren,
  ApiFortnoxArticleCleanupRoute: ApiFortnoxArticleCleanupRoute,
  ApiFortnoxPaymentTermsDiagnosticRoute: ApiFortnoxPaymentTermsDiagnosticRoute,
  ApiGmailDiagnosticRoute: ApiGmailDiagnosticRoute,
  ApiPushTestRoute: ApiPushTestRoute,
  BTokenRoute: BTokenRoute,
  BestallningarIdRoute: BestallningarIdRoute,
  CTokenRoute: CTokenRouteWithChildren,
  ProduktIdRoute: ProduktIdRoute,
  BestallningarIndexRoute: BestallningarIndexRoute,
  ApiPublicClientLogRoute: ApiPublicClientLogRoute,
  ApiPublicInvoicePdfRoute: ApiPublicInvoicePdfRoute,
  ScandicBookTokenRoute: ScandicBookTokenRoute,
  ApiPublicFortnoxCallbackRoute: ApiPublicFortnoxCallbackRoute,
  ApiPublicHooksChatRemindersRoute: ApiPublicHooksChatRemindersRoute,
  ApiPublicHooksElksIncomingRoute: ApiPublicHooksElksIncomingRoute,
  ApiPublicHooksPushRemindersRoute: ApiPublicHooksPushRemindersRoute,
  ApiPublicHooksScandicRemindersRoute: ApiPublicHooksScandicRemindersRoute,
  ApiPublicHooksSendDueOpportunitiesRoute:
    ApiPublicHooksSendDueOpportunitiesRoute,
  ApiPublicHooksVismaRunInvoicesRoute: ApiPublicHooksVismaRunInvoicesRoute,
  ApiPublicVismaCallbackRoute: ApiPublicVismaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
